---
- name: Hello World Example
  hosts: localhost
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: "Hello world, it's me in feature 9 and i'm doing changes. Change1 Should pass !"
