name: Call Shared Pull Request Workflow

on: [pull_request]

permissions:
  contents: write

jobs:
  call-shared-workflow:
    uses: AdrienMS-Cap/tst-shared-pipeline/.github/workflows/auto_merge.yml@main
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name }} 