name: Call Shared Pull Request Workflow

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  call-approve-workflow:
    uses: AdrienMS-Cap/tst-shared-pipeline/.github/workflows/approve.yml@main
    with:
      repository: ${{ github.repository }}
      pull_request_number: ${{ github.event.pull_request.number }}