name: Call Shared Workflow and Merge PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions: write-all

jobs:
  call-shared-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Call Shared Workflow
        uses: AdrienMS-Cap/tst-shared-pipeline/.github/workflows/create_workflow.yml@main
        with:
          repository: ${{ github.repository }}
          branch: ${{ github.ref_name }}

  auto-merge:
    needs: call-shared-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Merge Pull Request
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --squash
        env:
          GH_TOKEN: ${{ github.token }}
