name: Call Shared Workflow

on: 
  push:
  pull_request:

jobs:
  call-shared-workflow:
    if: github.event_name == 'push'
    uses: AdrienMS-Cap/tst-shared-pipeline/.github/workflows/create_workflow.yml@main
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name }}

  call-pr-workflow:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Call PR Workflow
        uses: AdrienMS-Cap/tst-shared-pipeline/.github/workflows/pr_workflow.yml@main
        with:
          github-token: ${{ github.token }} # replace with your GitHub token
