name: Use Shared Ansible Lint Workflow

on: [push, pull_request]
permissions:
  contents: write
jobs:
  call-shared-workflow:
    uses: AdrienMS-Cap/tst-shared-pipeline/.github/workflows/ansible-lint.yml@main
    secrets: inherit
    with:
      repository: ${{ github.repository }}

  push-to-production:
    runs-on: ubuntu-latest
    needs: [call-shared-workflow]
    if: ${{ needs.call-shared-workflow.result == 'success' }}
    steps:
     - name: Checkout Main-Production Branch
      uses: actions/checkout@v2
      with:
        ref: main-production

    - name: Merge Triggering Branch
      run: |
        git fetch origin ${{ github.head_ref }}
        git merge origin/${{ github.head_ref }} --no-ff --no-commit

    - name: Push to Main-Production
      run: |
        git config user.name "mypipelienname"
        git config user.email "test@mail.com"
        git commit -m "Merged branch ${{ github.head_ref }} into main-production"
        git push origin main-production
  



# name: Use Shared Ansible Lint Workflow

# on:
#   push:
#     branches-ignore:
#       - main-production
#   pull_request:
#     branches:
#       - main
