name: Call Shared Ansible Lint Workflow

on: [push]

permissions:
  contents: write

jobs:
  call-shared-workflow:
    uses: AdrienMS-Cap/tst-shared-pipeline/.github/workflows/start_create_workflow.yml@main
    with:
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name }} 